# Generated by Django 4.0.5 on 2022-06-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('ExcerciseId', models.AutoField(primary_key=True, serialize=False)),
                ('ExcerciseName', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ExcerciseImage', models.ImageField(null=True, upload_to='images/', verbose_name='Imagen')),
                ('ExcerciseDescription', models.TextField(verbose_name='Imagen')),
                ('ExcerciseMuscle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Usernombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('UserHeight', models.FloatField()),
                ('UserWeight', models.FloatField()),
            ],
        ),
    ]
