# Generated by Django 4.0.5 on 2022-07-14 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excercise',
            name='ExcerciseDescription',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='excercise',
            name='ExcerciseMuscle',
            field=models.CharField(max_length=50, verbose_name='Musculo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserHeight',
            field=models.FloatField(verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserWeight',
            field=models.FloatField(verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Username',
            field=models.CharField(max_length=50, verbose_name='Username'),
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('RoutineId', models.AutoField(primary_key=True, serialize=False)),
                ('Routinename', models.CharField(max_length=50, verbose_name='Nombre Rutina')),
                ('RoutineExcercise', models.ManyToManyField(to='api.excercise')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('HistoryId', models.AutoField(primary_key=True, serialize=False)),
                ('Usernombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('HistoryWeight', models.FloatField(verbose_name='Peso')),
                ('HistoryDate', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('RoutineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.routine')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
