# Generated by Django 4.0.5 on 2022-07-17 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_excercise_excercisedescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='RoutineExcercise',
        ),
        migrations.AlterModelTable(
            name='excercise',
            table='api_excercise',
        ),
        migrations.CreateModel(
            name='RoutineExcercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.excercise')),
                ('Routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.routine')),
            ],
        ),
    ]
