# Generated by Django 4.0.5 on 2022-07-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_routine_routineexcercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='RoutineExcercise',
            field=models.ManyToManyField(to='api.excercise'),
        ),
        migrations.AlterModelTable(
            name='routine',
            table='api_routine',
        ),
        migrations.DeleteModel(
            name='RoutineExcercise',
        ),
    ]
