# Generated by Django 4.0.5 on 2022-07-18 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_routine_routineexcercise_alter_routine_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excercise',
            old_name='ExcerciseDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='excercise',
            old_name='ExcerciseId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='excercise',
            old_name='ExcerciseImage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='excercise',
            old_name='ExcerciseMuscle',
            new_name='muscle',
        ),
        migrations.RenameField(
            model_name='excercise',
            old_name='ExcerciseName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='routine',
            old_name='RoutineExcercise',
            new_name='excercise',
        ),
        migrations.RenameField(
            model_name='routine',
            old_name='RoutineId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='routine',
            old_name='Routinename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserHeight',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Usernombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserWeight',
            new_name='weight',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
